# Generated by Django 5.2.7 on 2025-10-13 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_id', models.UUIDField(db_index=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type', models.CharField(choices=[('internal', 'Internal Employee'), ('external', 'External User')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
            ],
            options={
                'db_table': 'auth_keycloak_users',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='auth_service.keycloakuser')),
            ],
            options={
                'db_table': 'auth_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('resource', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_service.keycloakuser')),
            ],
            options={
                'db_table': 'auth_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('keycloak_role_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(blank=True, related_name='roles', to='auth_service.keycloakuser')),
            ],
            options={
                'db_table': 'auth_roles',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit Access')], max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='permissions', to='auth_service.role')),
            ],
            options={
                'db_table': 'auth_permissions',
            },
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to='auth_service.group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.role')),
            ],
            options={
                'db_table': 'auth_group_roles',
            },
        ),
        migrations.AddIndex(
            model_name='keycloakuser',
            index=models.Index(fields=['keycloak_id'], name='auth_keyclo_keycloa_fd02ea_idx'),
        ),
        migrations.AddIndex(
            model_name='keycloakuser',
            index=models.Index(fields=['email'], name='auth_keyclo_email_ff3c97_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='auth_audit__user_id_581b94_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['event_type'], name='auth_audit__event_t_bc328d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('module', 'action', 'resource_type')},
        ),
        migrations.AlterUniqueTogether(
            name='grouprole',
            unique_together={('group', 'role')},
        ),
    ]
